apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgCm/vD/kynkulg7eHWM/eGLR5FV55+oS3aSRtxog7A/ImuMcF3HYFkDwXqynltSwMi2ojlG/gKHAAJNEf4N1dlRFyfJF6uAe13dd0UvQUmVhOd4WXXdo3S8IDNK0wbCoG1GBFaPBN6wMcDZnfPFnMNI1yZSINcKIHLCuQZNAmjTNRTRwDqP429hwcDihYdzsf5bmdd8BSR0lgLoUD6ntyA0i2qY2n5T3zJorWznL5wabEXdQzeRNVsdtWze1VwD6Otn+Kc1UsU34blFt8byC6qyL7WAqhqD9Bl1DMbPschkeysRn0Rc/suKTrY9REKVGrBG6UrucBFjxk82m0IxjS75CK0EqW8/mGRqs9Tz5CKWCUg2K/aYjfBx5tZ9JghRmyiIDN0yRz0mTk3IxIGbLVS+YHt2FAzfsf2vl0tv+E+Ole9l9oIt91qBL8i0yvGbJDGdX74tLjFypfX0IKmYhkP8HPrp/Oh3jaIb4MVo7HY9KzxmJ8geChwTPemBtvezni+a3f2OfajuGaiwQiNdYmVN38w0duzMv5Ob0DvwDIzlMMHrTkdkRR1vE9Kpp7W9sGGn+LPeXGwnQB9oKUvuJYWYcoqQy3uGx5BdGa1NIZ9TLFbd7p4DFw4LC2W1Bo1VAwsA3PKA5RsNtSYlprF25hMHHEdJoFLLG8tHLHwgoUrr0Jr68Z9LY5CS4Jc5OsO85UW0Ic+I+FlC54H05svR2ZUhcq/v2NhjegrFJASVhgdiWd+GL7iTVriI
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default

